accountLinking:
  enableAccountCreation: true
  linkingType: GOOGLE_SIGN_IN
category: UTILITIES
defaultLocale: en
localizedSettings:
  developerEmail: saheel97@gmail.com
  developerName: Saheel
  displayName: Reminder Assistant
  pronunciation: reminder assistant
projectId: checklistbot-b9f66
